export const ChoiceTypes = {
  WIN_ROCK: 'WIN_ROCK',
  LOOSE_ROCK: 'LOOSE_ROCK',
  TIE_ROCK: 'TIE_ROCK'
  // PAPER: 'CHOICE_PAPER',
  // SCISSORS: 'CHOICE_SCISSORS',
  // SPOCK: 'CHOICE_SPOCK',
  // LIZARD: 'CHOICE_LIZARD'
};
