export const ChoiceTypes = {
  WIN_ROCK: 'WIN_ROCK',
  LOSE_ROCK: 'LOSE_ROCK',
  TIE_ROCK: 'TIE_ROCK',
  WIN_PAPER: 'WIN_PAPER',
  LOSE_PAPER: 'LOSE_PAPER',
  TIE_PAPER: 'TIE_PAPER',
  WIN_SCISSORS: 'WIN_SCISSORS',
  LOSE_SCISSORS: 'LOSE_SCISSORS',
  TIE_SCISSORS: 'TIE_SCISSORS',
  WIN_SPOCK: 'WIN_SPOCK',
  LOSE_SPOCK: 'LOSE_SPOCK',
  TIE_SPOCK: 'TIE_SPOCK',
  WIN_LIZARD: 'WIN_LIZARD',
  LOSE_LIZARD: 'LOSE_LIZARD',
  TIE_LIZARD: 'TIE_LIZARD',
  API_CHOICE: 'API_CHOICE',
  CLEAR_SCOREBOARD: 'CLEAR_SCOREBOARD'
};
